### PR TITLE
Make sccache never time out

### PR DESCRIPTION
**Pull request by jdm**
This should fix https://github.com/servo/servo/issues/19495.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/763)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Are there docs for this somewhere? Please add a link to the commit message and also maybe a description of the problem (where is sccache timing out currently?) and/or link to a Buildbot log in this PR.

**Comment by jdm** [comment]
Commit message updated.

**Comment by aneeshusa** [comment]
Thanks for the links. Two questions I have:
- The `Jenkins.md` link recommends `start the server beside Jenkins as a system service` in addition to setting the environment variable in this PR. Do you know if this is required/what the effect is if we don't start sccache by ourselves as a system service (e.g. upstart or systemd)?
- We will need to upgrade sccache from time to time (e.g. #755). What is the story for handling these kinds of upgrades: do we need to perform manual steps, and if so, what are they? (Stopping the existing sccache process(es), starting new one(s), clearing cache data from disk, etc.)

**Comment by jdm** [comment]
The first time a build is run with a timeout of 0, it will automatically start the long-lived server in the background. As part of upgrading, we should run `sccache --stop-server` before installing the new version. Otherwise we should not need to do anything else. This PR should be mergeable as-is.

**Comment by jdm** [comment]
I'm going to go ahead and merge this change because https://github.com/servo/servo/issues/19495 is really frustrating and I want to have enough time to be able to look into anything that might go wrong.

@bors-servo: r+

**Pull request merged**
