### PR TITLE
Gate on forbidden additions of unwrap

### PR DESCRIPTION
**Pull request by jdm**
Note: this shouldn't merge until https://github.com/servo/servo/pull/10610 is merged, but then it should merge ASAP.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/317)

### CODE REVIEW

**Comment by KiChjang** [comment]
System power off?

**Comment by aneeshusa** [comment]
That's so weird, I have no idea what that could be. Hopefully it's intermittent.
@bors-servo retry

**Comment by aneeshusa** [comment]
BTW, I need to run to a midterm now so someone else should finish landing this + deploying it on our Buildbots.

**Pull request merged**
