### PR TITLE
Add kunalmohan to try users

### PR DESCRIPTION
**Pull request by kunalmohan**
I will be working on WebGPU CTS and having "try" permissions will be quite helpful.

### CODE REVIEW

**Comment by jdm** [comment]
Filed https://github.com/servo/saltfs/issues/1003 about the CI failures.

**Comment by jdm** [comment]
Try changing https://github.com/servo/saltfs/blob/90036502c8fac2291fba372b3309bafef605f5b2/salt/common.sls#L6-L8 as well.

**Comment by kunalmohan** [comment]
Some success, but still 2 failures

**Comment by kunalmohan** [comment]
I fail to understand why some tasks return `gpg: no valid OpenPGP data found.` and others `Ok`

**Comment by jdm** [comment]
Ok, I figured out why those two jobs are failing - the URLs for the archived salt versions don't include the patch release. I'm going to try upgrading us to a non-archived version instead in #1004.

**Comment by jdm** [comment]
This change has been deployed; you should be able to use try commands now.

**Pull request merged**
