### PR TITLE
Make android sdk 25.2.3 default

### PR DESCRIPTION
**Pull request by aneeshusa**
Follow up to servo/servo#15773.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/644)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
This has been deployed.

**Comment by aneeshusa** [comment]
@larsbergstrom I checked via Salt and the symlink is still pointing to `r24.4.1` on `cross1` and `cross2`; did you leave a log of the highstate for this?

Due to #684, it may be best to hold off on trying to redeploy this for the moment.

**Comment by larsbergstrom** [comment]
Linux 1:
```
lrwxrwxrwx 1 servo servo   31 Jun  7 18:41 current -> /home/servo/android/sdk/r25.2.3
drwxr-xr-x 7 servo servo 4096 May 31 04:08 r24.4.1
drwxr-xr-x 7 servo servo 4096 Apr 21 22:11 r25.2.3
root@ip-172-31-34-111:~# 
```

Linux2:
```
lrwxrwxrwx 1 servo servo   31 Jun  7 18:38 current -> /home/servo/android/sdk/r25.2.3
drwxr-xr-x 7 servo servo 4096 May 31 09:27 r24.4.1
drwxr-xr-x 7 servo servo 4096 Apr 21 20:57 r25.2.3
root@ip-172-31-43-142:~# 
```

so it *should* be fine?
```

**Pull request merged**
