### PR TITLE
Add 4/5 of the new macs

### PR DESCRIPTION
**Pull request by edunham**
See https://github.com/servo/saltfs/issues/674#issuecomment-303591568. 

Test that the 4 completed new builders are actually working, and free up a bit of capacity, while I finish up with mac9. 

Also format these lines to have less icky diffs as we add and remove others.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/677)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
You can r=me after it passes :-)

**Comment by jdm** [comment]
```
[ FAIL ] Buildbot master config lint check failed:

         ./buildbot/master/files/config/master.cfg:21:14: E124 closing bracket does not match visual indentation
```

**Comment by edunham** [comment]
oh gosh dangit it passed flake8 :/ fixing

**Comment by larsbergstrom** [comment]
That works for me. Can either r+ or squash and r+, whichever you prefer.

**Pull request merged**
