### PR TITLE
Use steps.Test instead of steps.Compile

### LINKED ISSUE #343: Use steps.Test instead of steps.Compile for './mach test-unit' on Windows
The Windows Buildbot factory has a hard-coded list of steps, since the heuristics added in #325 can't yet handle the extra Windows boilerplate. The second step runs `./mach test-unit`; until our heuristics are fixed (not so easy), this should be run as a `steps.Test` step instead of a `steps.Compile` step.
 
Files:
 - buildbot/master/files/config/factories.py

### PR DESCRIPTION
**Pull request by CorcovadoMing**
fix #343

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/345)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Please fix the lint error, looks good otherwise.

**Comment by CorcovadoMing** [comment]
Sorry about that, I've fixed the lint error, please have a look

**Comment by aneeshusa** [comment]
Great, this just needs a squash.

**Comment by aneeshusa** [comment]
Thanks for the PR!

@bors-servo r+

**Comment by aneeshusa** [comment]
Can you update the commit message so it only has the first line and doesn't mention the pep8 fix?

**Comment by CorcovadoMing** [comment]
@aneeshusa Sure :)

**Comment by aneeshusa** [comment]
@CorcovadoMing Sorry about that, thanks for your patience :)

@bors-servo r+

**Pull request merged**
