### PR TITLE
Add servo/osmesa-src

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @aneeshusa @edunham

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/484)

### CODE REVIEW

**Comment by aneeshusa** [comment]
r=me, not sure if you want to land servo/osmesa-src#3 first or this one first.

**Comment by larsbergstrom** [comment]
@bors-servo r=aneeshusa

Yeah, typically I like to land and deploy this first so that I can land the .travis.yml fix as the first "homu approved" bit :-)

**Comment by larsbergstrom** [comment]
Hrm, this is a weird error:
```
----------

          ID: disable-homebrew-analytics

    Function: git.config

        Name: homebrew.analyticsdisabled

      Result: False

     Comment: An exception occurred in this state: Traceback (most recent call last):

                File "/usr/local/Cellar/saltstack/2015.5.5_1/libexec/lib/python2.7/site-packages/salt/state.py", line 1561, in call

                  **cdata['kwargs'])

                File "/usr/local/Cellar/saltstack/2015.5.5_1/libexec/lib/python2.7/site-packages/salt/states/git.py", line 573, in config

                  is_global=is_global)

                File "/usr/local/Cellar/saltstack/2015.5.5_1/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 924, in config_set

                  return _git_run(cmd, cwd=cwd, runas=user)

                File "/usr/local/Cellar/saltstack/2015.5.5_1/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 99, in _git_run

                  'Command {0!r} failed. Stderr: {1!r}'.format(cmd, stderr))

              CommandExecutionError: Command 'git config homebrew.analyticsdisabled "true"' failed. Stderr: 'error: could not lock config file .git/config: No such file or directory'

     Started: 15:01:04.872080

    Duration: 20.949 ms

     Changes:   
```

**Comment by larsbergstrom** [comment]
And the other mac builder just froze & died:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by larsbergstrom** [comment]
r? @glennw 

This *should* work once it's retested. Linux is now succeeding, homu support is in place, and we just need to use the updated macOS image from Travis.

**Comment by aneeshusa** [comment]
@larsbergstrom, I think you may have commented on the wrong PR.

**Comment by larsbergstrom** [comment]
Thanks :-)

**Pull request merged**
