### PR TITLE
Add brew scripts to nightly

### PR DESCRIPTION
**Pull request by paulrouget**
Follow up of https://github.com/servo/servo/pull/12688

Also, see https://github.com/servo/servo/issues/12888

/cc @larsbergstrom

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/460)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
If we're going to make the changes on the saltfs side, we should also add the environment additions. Lemme hack up some quick scripts for that.

**Comment by larsbergstrom** [comment]
OK, do this:
```
[larsberg@larsberg saltfs]$ git diff
diff --git a/buildbot/master/files/config/environments.py b/buildbot/master/files/config/environments.py
index de93b59..d8c427f 100644
--- a/buildbot/master/files/config/environments.py
+++ b/buildbot/master/files/config/environments.py
@@ -1,6 +1,6 @@
 import copy
 
-from passwords import GITHUB_DOC_TOKEN
+from passwords import GITHUB_DOC_TOKEN, GITHUB_HOMEBREW_TOKEN
 from passwords import S3_UPLOAD_ACCESS_KEY_ID, S3_UPLOAD_SECRET_ACCESS_KEY
 
 
@@ -136,4 +136,5 @@ build_arm64 = build_arm + Environment({
 upload_nightly = Environment({
     'AWS_ACCESS_KEY_ID': S3_UPLOAD_ACCESS_KEY_ID,
     'AWS_SECRET_ACCESS_KEY': S3_UPLOAD_SECRET_ACCESS_KEY,
+    'TOKEN': GITHUB_HOMEBREW_TOKEN,
 })
diff --git a/buildbot/master/files/config/passwords.py b/buildbot/master/files/config/passwords.py
index 495aedf..3ebcf24 100644
--- a/buildbot/master/files/config/passwords.py
+++ b/buildbot/master/files/config/passwords.py
@@ -3,6 +3,7 @@ HTTP_PASSWORD = "{{ buildbot_credentials['http-pass'] }}"
 SLAVE_PASSWORD = "{{ buildbot_credentials['slave-pass'] }}"
 CHANGE_PASSWORD = "{{ buildbot_credentials['change-pass'] }}"
 GITHUB_DOC_TOKEN = "{{ buildbot_credentials['gh-doc-token'] }}"
+GITHUB_HOMEBREW_TOKEN = "{{ buildbot_credentials['gh-homebrew-token'] }}"
 HOMU_BUILDBOT_SECRET = "{{ buildbot_credentials['homu-secret'] }}"
 S3_UPLOAD_ACCESS_KEY_ID = \
     "{{ buildbot_credentials['s3-upload-access-key-id'] }}"
[larsberg@larsberg saltfs]$ 
```

Otherwise, the publish will fail.

**Comment by paulrouget** [comment]
"All checks have failed"

What am I doing wrong?

**Comment by KiChjang** [comment]
@paulrouget Not your fault, it looks like pip installation is failing on travis... again.

**Pull request merged**
