### PR TITLE
Make rustup update when specific version not present.

### PR DESCRIPTION
**Pull request by jdm**
This PR causes us to update to the most recent release of rustup, as a result.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/761)

### CODE REVIEW

**Comment by jdm** [comment]
r? @metajack 
cc @SimonSapin

**Comment by aneeshusa** [comment]
This current solution will cause new machines to fail to bootstrap if rustup publishes a newer version than 1.7.0.
I would want to have versioned-locked download URLs for reproducibility.
The long term goal here is versioned uploads of rustup itself, published by the rustup.rs repo (either S3 or GH releases).
In the meantime, we can manually mirror selected versions to a servo-controlled S3 bucket (we have a couple of them).
I would prefer to download rustup itself directly if it is a static binary on all platforms (similar to sccache), but if that is not possible it would also be acceptable to have versioned URLs for the rustup installer.

**Comment by SimonSapin** [comment]
I don’t think we should be in the business of hosting rustup binaries. We can parse the output of `rustup --version` to extract a tuple of integers, and check for a minimum version instead of an exact one.

**Comment by SimonSapin** [comment]
Something like…

```diff
-    - unless: rustup --version | grep '{{ rustup.version }}'
+    - unless: rustup --version |  python -c 'import sys, re; [int(i) for i in re.match("rustup (\d+).(\d+).(\d+) ", sys.stdin.read()).groups()] >= [1, 7, 0] or sys.exit(1)'
```

**Pull request closed without merging**
