### PR TITLE
Remove extraneous .tgz to fix ARM rootfs downloads

### PR DESCRIPTION
**Pull request by aneeshusa**
See this comment for context:
https://github.com/servo/saltfs/pull/268#issuecomment-201436029

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/278)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Let's wait to merge until after S3 is updated and we've carefully examined the Travis logs for the cross builder this time.

cc @larsbergstrom

**Comment by larsbergstrom** [comment]
```
[larsberg@lbergstrom saltfs]$ s3cmd cp s3://servo-rust/ARM/v1/armhf-trusty-libs.tgz s3://servo-rust/ARM/armhf-trusty-libs/v1/armhf-trusty-libs.tgz
remote copy: 's3://servo-rust/ARM/v1/armhf-trusty-libs.tgz' -> 's3://servo-rust/ARM/armhf-trusty-libs/v1/armhf-trusty-libs.tgz'
[larsberg@lbergstrom saltfs]$ s3cmd cp s3://servo-rust/ARM/v1/arm64-trusty-libs.tgz s3://servo-rust/ARM/arm64-trusty-libs/v1/arm64-trusty-libs.tgz
remote copy: 's3://servo-rust/ARM/v1/arm64-trusty-libs.tgz' -> 's3://servo-rust/ARM/arm64-trusty-libs/v1/arm64-trusty-libs.tgz'
[larsberg@lbergstrom saltfs]$ 
```

**Comment by aneeshusa** [comment]
@larsbergstrom That's still not quite right, double-check the changes I made. (Missing a version string in the filename).

**Comment by larsbergstrom** [comment]
Wow :-)

```
[larsberg@lbergstrom saltfs]$ s3cmd cp s3://servo-rust/ARM/v1/arm64-trusty-libs.tgz s3://servo-rust/ARM/arm64-trusty-libs/v1/arm64-trusty-libs-v1.tgz
remote copy: 's3://servo-rust/ARM/v1/arm64-trusty-libs.tgz' -> 's3://servo-rust/ARM/arm64-trusty-libs/v1/arm64-trusty-libs-v1.tgz'
[larsberg@lbergstrom saltfs]$ s3cmd cp s3://servo-rust/ARM/v1/armhf-trusty-libs.tgz s3://servo-rust/ARM/armhf-trusty-libs/v1/armhf-trusty-libs-v1.tgz
remote copy: 's3://servo-rust/ARM/v1/armhf-trusty-libs.tgz' -> 's3://servo-rust/ARM/armhf-trusty-libs/v1/armhf-trusty-libs-v1.tgz'
[larsberg@lbergstrom saltfs]$ 
```

**Comment by aneeshusa** [comment]
Thanks, looks like you uploaded it just in time for the Travis cross build to pick it up. (Please double check the logs to verify this.)

**Comment by larsbergstrom** [comment]
@bors-servo r+

Confirmed in the logs that they both downloaded & extracted fine :-)

**Pull request merged**
