### PR TITLE
homu: Let hiro land his PRs reviewed in bugzilla.

### PR DESCRIPTION
**Pull request by emilio**
He's been doing a lot of stylo work recently, and I got tired of delegating all
his patches :).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/652)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@emilio What does this specifically mean here? You're saying that he gets review for the Servo bits in some other place and needs the ability to `r=emilio` them here without having one of you do it?

Sorry for being a bit dense here - the text of this PR and the commit are asking for him to get reviewer privs, which requires review of some of their reviews, and to be allowed to self-`r+`, which is not allowed in Servo, so I'm a little confused :-)

**Comment by hiikezoe** [comment]
@larsbergstrom It's enough to me that I have the permission to do delegate+ for PRs that patches have been already reviewed in bugzilla.

**Comment by emilio** [comment]
Right, so this PR puts him in the `operator` list, in order to land his reviewed-in-bugzilla PRs.

Sorry, wasn't trying to imply self-r+.

**Comment by larsbergstrom** [comment]
Thanks, that will be fine, then :-)

@bors-servo r+

**Comment by aneeshusa** [comment]
FYI, I have deployed this so bors-servo should now recognize your new permissions.

**Pull request merged**
