### PR TITLE
Add Emilio's key.

### PR DESCRIPTION
**Pull request by emilio**
In order to debug and try to reproduce the issues in
https://github.com/servo/servo/pull/12858

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/461)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Sorry I forgot to mention you also need to be added to:
https://github.com/servo/saltfs/blob/c1d73d73c26a09519d8093f2a0c8e913b576ed85/common/map.jinja#L14

**Comment by emilio** [comment]
Done, thanks!

**Pull request merged**
