### PR TITLE
Add linux and osx nightly builds

### PR DESCRIPTION
**Pull request by aneeshusa**
Alternative to #409 that is more secure IMO.
Requires servo/servo#11943.

cc @larsbergstrom @edunham

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/410)

### CODE REVIEW

**Comment by aneeshusa** [comment]
I was going to submit this as a PR to #409 but the changes didn't end up having that much in common.

**Comment by larsbergstrom** [comment]
this looks good to me after we land servo/servo#11943

**Comment by aneeshusa** [comment]
Deployment note: This requires pillar changes to work.

**Comment by aneeshusa** [comment]
Got Vagrant up so I can test this, hold off for one minute while I get the tests passing since Travis is a bit slow right now.

**Comment by aneeshusa** [comment]
@bors-servo r=larsbergstrom

servo/servo#11943 needs to be merged before deploying this.

**Pull request merged**
