### PR TITLE
Replaced hard coded color with RED constant from utils.py

### PR DESCRIPTION
**Pull request by leahnp**
This is to fix: https://github.com/servo/saltfs/issues/378 

https://github.com/servo/saltfs/pull/381 had been closed due to inactivity so I picked this task to start contributing to servo. Hopefully this resolves the outstanding comments from 381.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/400)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Thanks for the PR, and welcome to Servo! One quick nit: can you put `RED` at the end of the import list instead of the beginning? It looks a little strange in the front by the all-lowercase imports.

Looks good otherwise.

**Comment by leahnp** [comment]
Thanks for the quick reply! I've reordered the import and pushed a new commit.

**Comment by aneeshusa** [comment]
Great, please squash these commits together.

**Comment by leahnp** [comment]
OK, commit squashed.

**Pull request merged**
