### PR TITLE
Allow birtles to use try and land PRs

### PR DESCRIPTION
**Pull request by birtles**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/668)

### CODE REVIEW

**Comment by birtles** [comment]
Hi, I'd like to get permission to land PRs so I don't have to keep asking for delegate+ for Bugzilla-reviewed patches.

**Comment by aneeshusa** [comment]
@birtles Since you're updating the operator list, can you please fix the alphabetization (broken by #667) as well?

**Comment by birtles** [comment]
Yes, of course. Fixed.

**Pull request merged**
