### PR TITLE
Create error summary logs when running wptrunner-based tests

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/310)

### CODE REVIEW

**Comment by aneeshusa** [comment]
You'll need to update the `logfiles` parameter as well for each `ShellCommand` so Buildbot knows to capture the new log files. Other than that, LGTM.

**Comment by Ms2ger** [comment]
@jgraham ping

**Comment by jgraham** [comment]
Done. Sorry missed this review in the first instance.

**Pull request merged**
