### PR TITLE
Switch linux builders to EC2

### PR DESCRIPTION
**Pull request by metajack**
This also rolls up some of the other changes that weren't landed in separate commits.

r? @larsbergstrom or @edunham

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/98)

### CODE REVIEW

**Comment by metajack** [comment]
Note that this config has been running in production for a few weeks.

**Comment by Ms2ger** [comment]
Well then.

@bors-servo r+

**Comment by Manishearth** [comment]
wait. oh. this PR is not merging to master.

**Pull request closed without merging**
