### PR TITLE
Use functions in master.cfg to share code between factory definitions.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/110)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Tested in prod.

**Comment by metajack** [comment]
r=me if you fix the typo in the first commit message.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/saltfs/110)

**Comment by metajack** [comment]
Wait, bors-servo accepted a typo of my name??

**Comment by metajack** [comment]
I guess if you are a reviewer it doesn't care about what's after r=.

**Pull request merged**
