### PR TITLE
Add tigercosmos to try operators.

### PR DESCRIPTION
**Pull request by jdm**
@tigercosmos has been submitting a bunch of pull requests that require experimenting with the build machine environments. Let's given them direct access!

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/749)

### CODE REVIEW

**Comment by emilio** [comment]
👍 

@bors-servo r+

**Comment by tigercosmos** [comment]
Thanks!

**Comment by tigercosmos** [comment]
What is the next time it will deploy?

**Comment by jdm** [comment]
It is now deployed.

**Pull request merged**
