### PR TITLE
updated version of the NDK

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @edunham 
I think this gets overridden by the env variables set by the buildbot master.cfg, but it was bugging me to have these incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/260)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Heads up - sorry about the delay, but I'm almost ready to put in the PR I mentioned about updating Android in #239. Two things:

- I'm pretty sure that the `bash_profile` file is only used to set these environment variables for interactive usage, not buildbot. Does anybody use these? If not, I'd be ok with getting rid of this file.
- The changes in my PR will make this PR redundant, so let's hold off on merging this one.

**Comment by larsbergstrom** [comment]
@aneeshusa That's awesome! I didn't want to bug you about the PR, as I assumed you were busy :-) This will be a huge help. @edunham and I have a fairly comprehensive idea about everything that's currently broken in the Android rules, from bloody experience.

I'll just close this in favor of your work.

Also, you're correct that we shouldn't need the `bash_profile` anymore.

**Comment by aneeshusa** [comment]
If we don't need the bash_profile, I'll go ahead and get rid of it in the other PR.

**Comment by aneeshusa** [comment]
Also, feel free to poke me about stuff like that - I did have a busy week but I've got free time this week.

If there's anything else broken with the Android rules that isn't covered by my PR, please open some issues or let me know!

**Pull request closed without merging**
