### PR TITLE
replacing "31" with RED constant

### PR DESCRIPTION
**Pull request by d-jh**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/381)

### CODE REVIEW

**Comment by emilio** [comment]
This looks good to me, but it seems that travis complains:

```
./tests/lint/trailing_whitespace.py:11:18: F821 undefined name 'RED'
```

You should import the constant it seems.

**Comment by d-jh** [comment]
How is that?

**Comment by aneeshusa** [comment]
@d-jh Thanks for the PR! @emilio is correct that you need to import the constant. Instead of using `*` to import everything, please add `RED` to the list of imports instead. Using the glob-style import makes it impossible to know what you're importing from where, which causes problems over time as files get bigger and definitions move around.

**Comment by jdm** [comment]
@d-jh Are you planning to finish this up?

**Comment by KiChjang** [comment]
Closing due to lack of reply for 23 days.

**Pull request closed without merging**
