### PR TITLE
Add angle repo support

### PR DESCRIPTION
**Pull request by larsbergstrom**
@emilio Can you confirm if you want AppVeyor support or not, too? (I've got it in this PR)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/392)

### CODE REVIEW

**Comment by emilio** [comment]
Sounds great! That part should be covered by google/angle, but it doesn't hurt! :)

**Comment by larsbergstrom** [comment]
OK!

r? @edunham @aneeshusa

**Comment by aneeshusa** [comment]
Doesn't servo/angle#9 need to land first? (I don't know anything about Appveyor, so can't review it myself.)

**Comment by edunham** [comment]
r=me once https://github.com/servo/angle/pull/9 lands. Should we have bors+highfive on our Angle fork, too?

**Comment by emilio** [comment]
I'd have expected to land first homu appveyor support, and later land the pr with the `appveyor.yml` file to ensure it passes, though if you prefer the other way around feel free to merge https://github.com/servo/angle/pull/9 manually and then land this.

**Comment by aneeshusa** [comment]
servo/angle#9 has landed.
@bors-servo r=edunham

**Pull request merged**
