### PR TITLE
Run WPT tests in debug mode

### PR DESCRIPTION
**Pull request by nox**
This lets us use debug_assert!() in Servo. Tests should be run fast enough now that Servo improved.

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/107)

### CODE REVIEW

**Comment by Manishearth** [comment]
You're adding steps to the release builders; they'll build Servo in release, and then build it again in debug to make wpt work. Not what we want :smile:

**Comment by nox** [comment]
Oh, I need to build debug too I guess?

**Comment by nox** [comment]
Isn't the configuration a mess? I think linux_dev_factory and mac_dev_ref_unit_factory are defined twice.

**Comment by metajack** [comment]
If you want to switch to dev builds, then you should also rename the factories to match. Calling it linux_rel_factory when it builds dev is not the best.

Also, running wpt in debug mode when everything is compiled in release mode will about double our compile times (since it will have to do it twice).

Probably we should switch to running everything in debug. Later we can add new slaves and expand to cover release mode again.

**Comment by nox** [comment]
Rebased and amended, I also renamed the factories and builders accordingly.

**Comment by Ms2ger** [comment]
How about the CSS tests? Did they improve as well?

**Comment by nox** [comment]
@Ms2ger I have absolutely no idea. In doubt, I didn't change it.

**Comment by Ms2ger** [comment]
Except you did on Linux

**Comment by nox** [comment]
I have no idea what you mean. Where did I change test-css?

**Comment by nox** [comment]
Oh right, it's right in the middle of it!

**Comment by nox** [comment]
So I guess I need to either change the other tests to stay consistent, or to move CSS tests on Linux in a separate factory?

**Comment by metajack** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/saltfs/107)

**Comment by metajack** [comment]
You should change the mac-rel-css factory to mac-dev-css. That will make everything consistent. r=me with that change.

**Pull request merged**
