### PR TITLE
Add appveyor support for servo's homu

### PR DESCRIPTION
**Pull request by Manishearth**
Don't merge yet, needs https://github.com/servo/homu/pull/13 to merge and then a bump in the homu SHA
r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/232)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
r=me after SHA bump

**Comment by larsbergstrom** [comment]
```
          ID: android-dependencies

    Function: pkg.installed

      Result: False

     Comment: An error was encountered while installing package(s): W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

              

              E: Some index files failed to download. They have been ignored, or old ones used instead.

     Started: 16:53:16.581770

    Duration: 3715.043 ms

     Changes:   
```

**Comment by aneeshusa** [comment]
Google has dropped support for 32-bit Chrome (planned for March hence the sudden breakage): http://www.omgubuntu.co.uk/2016/03/fix-failed-to-fetch-google-chrome-apt-error-ubuntu

Is there any reason we need Chrome? If not, I'd rather remove it entirely than trying to modify the appropriate `.list` file to only try to get the 64-bit builds.

**Comment by Manishearth** [comment]
We don't explicitly mention Chrome anywhere. I don't know why it tries to download chrome.

**Comment by aneeshusa** [comment]
I checked via Salt on the builders and you're right, none of our machines have chrome in their apt sources.
The error only happens on the machines with multi-arch enabled, which is the 2 android related machines. My hunch is that the Travis builders have chrome in their sources. I'll try it out in Vagrant to see if that's the case.

**Comment by aneeshusa** [comment]
Yup, looks ok in Vagrant. I'll put in a test PR to check Travis.

**Comment by aneeshusa** [comment]
See #233 for the Travis test PR

**Pull request merged**
