### PR TITLE
Make gterzian a reviewer.

### PR DESCRIPTION
**Pull request by jdm**
@gterzian has gained experience with many different parts of the codebase and provides lots of useful feedback on pull requests already. I think it's time to grant him the full powers of reviewership!

### CODE REVIEW

**Comment by jdm** [comment]
@gterzian If you would like to have the powers of a Servo reviewer and can follow the guidelines at https://github.com/servo/servo/wiki/Reviewer and https://github.com/servo/servo/wiki/Code-review, let us know :)

**Comment by gterzian** [comment]
Thank you, I have looked at the guidelines and I would like to accept :)

**Comment by jdm** [comment]
Deployed.

**Pull request merged**
