### PR TITLE
Remove steps.yml from saltfs

### PR DESCRIPTION
**Pull request by aneeshusa**
These now live in the main servo/servo repo.

r? @larsbergstrom 
I'd like to have at least one PR build + be merged with the new configuration before removing the steps in case we need to revert/quickfix.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/513)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
(Just noticed that we don't have a PR pending - I assumed ONE must have gone through by now, but was wrong...)

**Comment by larsbergstrom** [comment]
Hrm, yeah, there's a failure, but just on `windows-dev`:
http://build.servo.org/builders/windows-dev/builds/1568

**Comment by aneeshusa** [comment]
Taken care of in #522.

**Pull request closed without merging**
