### PR TITLE
Add colon for python if

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @edunham 

cc @paulrouget

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/465)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
This is already deployed.

**Comment by aneeshusa** [comment]
r=me (although Travis is failling for unrelated reasons right now)

**Comment by aneeshusa** [comment]
Side question @larsbergstrom: how did you deploy this? I didn't see any trace of this code on `servo-master1`, although it is deployed.

**Comment by larsbergstrom** [comment]
Had to manually edit the files in `~servo/buildbot`, since we also couldn't highstate so I couldn't do the usual "edit /srv/salt" hackery.

**Comment by aneeshusa** [comment]
Right, so as part of #350 the way to make local changes has also changed, `/srv/salt` is no longer used. See the ADMIN_README file I added in that PR, ask on IRC with any questions.

**Pull request merged**
