### PR TITLE
Revert the DynamicServoFactory stuff

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @aneeshusa 

I need to just revert it all until we can sort out what's going on.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/515)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Can you leave the "Fix steps reading on windows" commit for now? I want to spin up a `windows-dev-yaml` test builder to get it working.

**Comment by larsbergstrom** [comment]
Done!

**Comment by aneeshusa** [comment]
@bors-servo r+

I have some ideas about the new Windows failures - expect more PRs soon.

**Comment by larsbergstrom** [comment]
Passed on all but mac; merging :-)

**Pull request merged**
