### PR TITLE
Add video-metadata-rs dependencies

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/428)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc https://github.com/servo/servo/pull/12186

**Comment by notriddle** [comment]
*[servo-build-dependencies/init.sls, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/saltfs/428#-KLviUMhSkv4fJ2SWYSm:-KLviUMhSkv4fJ2SWYSn:-1692303664) ([raw file](https://github.com/servo/saltfs/blob/bf65d0fa1e3b531691f37f0166780a447b6b32d7/servo-build-dependencies/init.sls#L13)):*
> ```Scheme
>       - pkg-config
>       - openssl
>       - freetype
> ```

Don't we need to install these things on macOS as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Comment by notriddle** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Comment by GuillaumeGomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[servo-build-dependencies/init.sls, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/saltfs/428#-KLviUMhSkv4fJ2SWYSm:-KLvjwJqPBRe1sRKhjy_:1042347720) ([raw file](https://github.com/servo/saltfs/blob/bf65d0fa1e3b531691f37f0166780a447b6b32d7/servo-build-dependencies/init.sls#L13)):*
<details><summary><i>Previously, notriddle (Michael Howell) wrote…</i></summary>
> Don't we need to install these things on macOS as well?
</details>
I'm not sure how to do actually. On my video-metadata-rs crate, I do like this: https://github.com/GuillaumeGomez/video-metadata-rs/blob/master/.travis.yml#L24-L25

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Comment by notriddle** [comment]
*[servo-build-dependencies/init.sls, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/saltfs/428#-KLviUMhSkv4fJ2SWYSm:-KLvmpRW3bJY0qGBEmtN:-683603218) ([raw file](https://github.com/servo/saltfs/blob/bf65d0fa1e3b531691f37f0166780a447b6b32d7/servo-build-dependencies/init.sls#L13)):*
<details><summary><i>Previously, GuillaumeGomez (Guillaume Gomez) wrote…</i></summary>
> I'm not sure how to do actually. On my video-metadata-rs crate, I do like this: https://github.com/GuillaumeGomez/video-metadata-rs/blob/master/.travis.yml#L24-L25
</details>
I'm pretty sure the pkgs list is homebrew packages under mac. But I'm not sure how to do the --with-libvpx argument. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Comment by GuillaumeGomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[servo-build-dependencies/init.sls, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/saltfs/428#-KLviUMhSkv4fJ2SWYSm:-KLvnKJeGtVX3fE11oUi:-2138380217) ([raw file](https://github.com/servo/saltfs/blob/bf65d0fa1e3b531691f37f0166780a447b6b32d7/servo-build-dependencies/init.sls#L13)):*
<details><summary><i>Previously, notriddle (Michael Howell) wrote…</i></summary>
> I'm pretty sure the pkgs list is homebrew packages under mac. But I'm not sure how to do the --with-libvpx argument. 
</details>
That was my point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Comment by GuillaumeGomez** [comment]
Thanks to [video-metadata-rs/14](https://github.com/GuillaumeGomez/video-metadata-rs/pull/14), we now know we can compile without `libvpx`.

**Comment by notriddle** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/428)*

**Pull request merged**
