### PR TITLE
notify travis status in servo-bots channel

### PR DESCRIPTION
**Pull request by edunham**
this is the other half of fixing https://github.com/servo/saltfs/issues/376 

i have already turned on nightly builds via travis's experimental cron feature

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/598)

### CODE REVIEW

**Comment by aneeshusa** [comment]
What is the `#servo-bots` channel? Is there someone (a human) monitoring this so we find out about failed nightly builds?

**Comment by edunham** [comment]
#servo-bots is a channel where all of Servo's bots dump information, so that we can use our IRC clients to filter those notifications which we care about. Jack and I idle in there, and others are welcome to as well. 

Dropping notifications into the bots channel basically just makes it easy to "subscribe" to whatever subset of notifications we each find relevant, while making sure we don't clutter the channels which exist for human conversation.

**Comment by aneeshusa** [comment]
OK, the only other suggestion I had was maybe using `on_success` and `on_failure` to pre-filter which notifications Travis sends to IRC, but if you're filtering in your client it's not necessary. r=me with or without that.

**Pull request merged**
