### PR TITLE
Add taskcluster status checking to webrender

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @edunham 

See below for an example of status output for an auto-push with Taskcluster test run:
https://api.github.com/repos/servo/webrender/commits/e582ec8/status

cc @jrmuizel @glennw @aneeshusa

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/776)

### CODE REVIEW

**Comment by jrmuizel** [comment]
Looks good to me. Assuming that @edunham is on PTO today can we land this now and do a post commit review tomorrow?

**Comment by glennw** [comment]
@jdm @larsbergstrom Is this needed? TC + WR + bors seem to be working happily now - does that add something extra?

**Comment by jdm** [comment]
I believe this change makes bors actually _gate_ on TC. Without it, the merge could happen as soon as appveyor finishes build successfully.

**Comment by larsbergstrom** [comment]
@glennw I did yolo-ops on the server. If we don't get this fix landed, the next time somebody makes a homu change and does a highstate, you'll lose WR gating on TC.

**Comment by larsbergstrom** [comment]
I'm very tempted to just merge this. We have a pass on the PR itself (https://travis-ci.org/servo/saltfs/builds/329179115?utm_source=github_status&utm_medium=notification) but the combination of mac and salt server instability is breaking the test runs one after another.

**Comment by jdm** [comment]
I think it's worth pushing the button.

**Comment by larsbergstrom** [comment]
Ugh, needed a rebase and now have to wait for status checks. lol :-)

**Comment by jdm** [comment]
Deployed.

**Pull request merged**
