### PR TITLE
Give @pyfisch try access.

### PR DESCRIPTION
**Pull request by emilio**
He's been doing some pretty neat work in the style system, and also some rendering features, like https://github.com/servo/servo/pull/16385.

He claims his computer is not ultra-fast in order to run all the tests, and I think we should give him try access in order to improve the situation.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/637)

### CODE REVIEW

**Comment by jdm** [comment]
Agreed!
@bors-servo: r+

**Comment by pyfisch** [comment]
Thank you, this helps me a lot. :smile:

**Comment by pyfisch** [comment]
How often is bors-servo updated and I can do `@bors-servo try`?

**Comment by jdm** [comment]
It requires someone to deploy the latest changes. It should happen in the next 12 hours.

**Pull request merged**
