### PR TITLE
Update sccache to 0.2.7

### PR DESCRIPTION
**Pull request by SimonSapin**
This hopefully works around https://github.com/rust-lang/cargo/issues/6269

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/911)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
upload: ./0.2.7-sccache-x86_64-apple-darwin to s3://servo-deps/sccache/0.2.7-sccache-x86_64-apple-darwin
upload: ./0.2.7-sccache-x86_64-pc-windows-msvc to s3://servo-deps/sccache/0.2.7-sccache-x86_64-pc-windows-msvc
upload: ./0.2.7-sccache-x86_64-unknown-linux-musl to s3://servo-deps/sccache/0.2.7-sccache-x86_64-unknown-linux-musl

**Comment by jdm** [comment]
Looks like you need to make the new files public:
```
----------
          ID: sccache
    Function: file.managed
        Name: /usr/local/bin/sccache
      Result: False
     Comment: Failed to cache https://servo-deps.s3.amazonaws.com/sccache/0.2.7-sccache-x86_64-unknown-linux-musl: Error: HTTP 403: Forbidden reading https://servo-deps.s3.amazonaws.com/sccache/0.2.7-sccache-x86_64-unknown-linux-musl
     Started: 15:14:32.439584
    Duration: 179.893 ms
     Changes:   
```

**Comment by jdm** [comment]
@bors-servo retry
Did that through the s3 console.

**Pull request merged**
