### PR TITLE
Add step to ensure Buildbot checks out right commit

### PR DESCRIPTION
**Pull request by aneeshusa**
We are using `retryFetch=True` to have Buildbot retry git fetches if
they error out, as we often encounter intermittent errors (e.g. network
problems).

However, Buildbot will allow not only the first fetch + checkout to
fail, but also the second (final) fetch + checkout to fail as well
(which I consider a bug in Buildbot), making it possible for Buildbot
to run a build on the wrong revision, causing confusion.

Retrying failed fetches is too useful to disable.
Hence, to work around this, add a custom step to all builds that checks
if the commit we requested (the `revision` property) matches the
actual commit Buildbot checks out, and fail the build if not the case.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/531)

### CODE REVIEW

**Comment by aneeshusa** [comment]
cc @jdm 
Will cause Buildbot to complain loudly if #530 happens again.

r? @larsbergstrom

**Comment by larsbergstrom** [comment]
This is awesome! Thanks for doing this. I'm willing to give this a try - should really help! Just one issue:
```
  ./buildbot/master/files/config/factories.py:37:16: E711 comparison to None should be 'if cond is not None:'
```

**Comment by aneeshusa** [comment]
Fixed the nit. I haven't seen this happen too many times in the past (I'm hoping it didn't just silently happen!) so I'm not sure how helpful this is, but it does give me more peace of mind.

**Pull request merged**
