### PR TITLE
Add web service for tracking intermittent failure instances

### PR DESCRIPTION
**Pull request by jdm**
This sets up an instance of https://github.com/servo/intermittent-failure-tracker/ on servo-master1 to allow the `./mach filter-intermittents` command to report instances of intermittent failures that are encountered on our build machines.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/739)

### CODE REVIEW

**Comment by jdm** [comment]
Added documentation.

**Comment by metajack** [comment]
This is deployed.

**Pull request merged**
