### PR TITLE
Add backticks to style guide

### PR DESCRIPTION
**Pull request by ManishBot**
[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/160)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/saltfs/160)

**Comment by Manishearth** [comment]
oh, right, I'd cancelled the build

**Pull request merged**
