### PR TITLE
Add geckolib dev build for windows.

### PR DESCRIPTION
**Pull request by emilio**
cc @bholley
r? @aneeshusa

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/435)

### CODE REVIEW

**Comment by upsuper** [comment]
I guess you probably should put `./mach build-geckolib` after `./mach test-unit`, which is the order elsewhere in that file.

**Comment by emilio** [comment]
@upsuper yep, that makes sense, done.

We *might* want also a release build, though IIRC windows is the slowest machine (so I don't know if it's doable without slowing all the queue).

Probably @larsbergstrom can tell us, and also maybe review it :)

**Comment by larsbergstrom** [comment]
Nah, that's fine. Windows is only 18 minutes (http://build.servo.org/builders/windows/builds/1700), so we've got plenty of time budget to add other things, given the 40 minute long poles of linux & mac release builds w/ WPT testing.

**Pull request merged**
