### PR TITLE
Update gstreamer binaries with gst-gl and updated glib

### PR DESCRIPTION
**Pull request by ferjm**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/944)

### CODE REVIEW

**Comment by ferjm** [comment]
This is already deployed.

**Comment by ferjm** [comment]
This failed for https://github.com/servo/servo/pull/22944 because the directory structure of the bundle containing the binaries changed in https://github.com/servo/media/pull/201/files I am updating the config to take that change into account.

**Comment by jdm** [comment]
@bors-servo r-
Waiting until the servo PR succeeds.

**Pull request merged**
