### PR TITLE
Move most Salt docs in tree

### PR DESCRIPTION
**Pull request by aneeshusa**
This also includes Vagrant information,
and should cover all the steps of a normal Salt workflow.

This does not (yet) include information about
setting up new Salt masters/minions,
or how to restart various services cleanly after a deploy.

r? @edunham @larsbergstrom 
cc @Ms2ger per [this comment](https://github.com/servo/saltfs/issues/545#issuecomment-263861942)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/549)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
I think I'm generally OK with this.

@edunham what do you think?

**Comment by edunham** [comment]
As long as we replace the corresponding wiki docs with pointers to the docs in tree, I'm fine with this. 

My only concern is that if we end up with parallel sets of docs on the same topic, one or the other will fall out of date and deciding which to follow becomes an unnecessary burden.

**Comment by aneeshusa** [comment]
Yes, I'll replace those sections on the wiki with references to the in-tree docs after this merges.

Thanks for looking over this! @bors-servo r=edunham

**Comment by aneeshusa** [comment]
I updated the Buildbot and SaltStack Administration pages on the wiki to remove the duplicate information and add pointers to the in-tree docs.

**Pull request merged**
