### PR TITLE
Use yaml for buildbot steps

### PR DESCRIPTION
**Pull request by aneeshusa**
A bunch of changes here including various removals and rearrangements; I'd recommend checking this commit by commit (including commit messages).

This a) simplifies the Buildbot master configuration and b) uses YAML to configure build steps instead of Python code. This allows us to PR the YAML file over to the main servo repo for #316; I'd like to see this landed before working on the rest of #316.

cc @edunham @shinglyu

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/325)

### CODE REVIEW

**Comment by jdm** [comment]
Having not looked at any of the rest of the implmentation, that's a really nice YAML configuration file!

**Comment by aneeshusa** [comment]
A note I left myself yesterday:

We don't need the `GITHUB_STATUS_TOKEN` pillar value anymore, so when this lands, we need to do the following:

- [ ] Revoke the token (if it's still valid) (unless it's getting used for homu...)
- [ ] Remove the value from the production pillar

**Comment by aneeshusa** [comment]
Also, to check that this works properly you can rename `master.cfg` to `master.py`, then in a Python2 repl `import master` and peruse the `master.c['builders']` object - I found this helpful while testing.

**Comment by larsbergstrom** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/saltfs/325#-KFf3LUy2-gQcM8wqsqa:-KFf3LUy2-gQcM8wqsqb:-686577304) (no related file):*
Can you please remove the `pkill` commit? It hasn't done so in a while, but it catches when `servo` processes spin out of control occasionally, so I'm loathe to remove it until we do something like reboot or image staging per-PR.

---

*[a discussion](https://reviewable.io:443/reviews/servo/saltfs/325#-KFf3alCw6AKL05wXMVK:-KFf3alCw6AKL05wXMVL:1107554539) (no related file):*
I think we need to keep the "duplicate" tests for manifest/lock file changes. They need to be run multiple times, because cargo can update different Cargo.lock files differently on different platforms and release vs. debug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/325)*

**Comment by larsbergstrom** [comment]
This is an awesome PR! @edunham and I just spent some time reviewing it line by line and were in awe of how much cleaner everything will be after this. Nice work!

**Comment by edunham** [comment]
These changes are beautiful, and were uniquely easy to review because of how well you structured your commits. Now our only changes are lines to add back into `steps.yml`, as Lars has mentioned: 

 * We do still need to `pkill -x servo` at the start or end of every build, or the platform-specific equivalent, because sometimes unusual test failures leave servo processes lying around. 
* We'd prefer to keep running the "duplicate" tests for now, to catch subtle differences between platforms

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/325#-:-KFf4DOLqYb0NUS1wlNQ:1262783618)*

**Comment by aneeshusa** [comment]
Thanks, I'm a stickler for using git commits + messages effectively :)

Quick question about keeping the duplicates - the only two tests that should be duplicated are `lockfile_changed.sh` and `manifest_changed.sh`, not `test-tidy` or `check_no_unwrap.sh`, correct? Also, `lockfile_changed.sh` just runs `git diff`, so why would its results be platform specific?

**Comment by larsbergstrom** [comment]
Yes, just lockfile/manifest_changed.

The Cargo.lock file contains a list of all of the crates and versions used across all platforms. But, in a given platform-specific build, only a subset of those might get touched. Further, different platforms (cef, stylo, servo, and gonk) even have their own different Cargo.lock files that are *only* touched on those builds! That check tends to catch errors on builds that are not performed by the original author (e.g., MacOS package updates for people who only have linux).

**Comment by Manishearth** [comment]
This seems to get rid of the `logfiles` stuff we had? Perhaps we should add an extra `logfiles` key to the YAML?

**Comment by aneeshusa** [comment]
@Manishearth the DynamicServoFactory.make_step method uses a little magic - sorry, heuristics :wink: - to automatically populate the logfiles parameter when necessary by looking for `--log-something` arguments to `./mach`. The logfiles parameter is easy to miss - see #310 for an example - but our usage of `mozlog` means this catches every important logfile so far.

In the future, we can make `make_step` smarter to handle explicit configuration of logfiles and such in the YAML file fairly easily, but I'd prefer to avoid that until we really need it.

**Comment by aneeshusa** [comment]
@larsbergstrom should we be running the lockfile and manifest checks on all the other builders as well, e.g. `arm32` and `arm64` and `android`?

**Comment by Manishearth** [comment]
Yes, because each platform might pull in platform-specific packages which won't have been updated in the committer's lockfile.

**Comment by aneeshusa** [comment]
What's the equivalent of `pkill` for Windows?

**Comment by aneeshusa** [comment]
Added back pkill (note, it's first removed then added back in a later commit), and updated the steps.yml file.

I also added a few TODO comments to do both of those things for Windows as well.

**Comment by larsbergstrom** [comment]
@aneeshusa `taskkill`, https://technet.microsoft.com/en-us/library/bb491009.aspx

I think we want `taskkill /im servo.exe`, but will check it out tomorrow when I'm in front of my Windows VM.

**Comment by larsbergstrom** [comment]
But yes, feel free to skip it on Windows for now!

**Comment by aneeshusa** [comment]
Fixed the build error.

**Comment by edunham** [comment]
Reviewable just made me go through every commit again, but showed everything unchanged from before you rebased as being empty diffs. Still looks good, though :)

---

Reviewed 9 of 9 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 1 of 1 files at r17, 3 of 3 files at r18, 1 of 1 files at r19, 4 of 4 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, 8 of 8 files at r23, 1 of 1 files at r24, 3 of 3 files at r25, 1 of 1 files at r26, 4 of 4 files at r27, 2 of 2 files at r28, 2 of 2 files at r29, 1 of 1 files at r30.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/325#-:-KFgJIAtzG-_CYsKRIbo:-1361344851)*

**Comment by shinglyu** [comment]
Do we need to quote the commands in the yaml file? We might have some steps that has special characters that may be parsed incorrectly?

**Comment by Manishearth** [comment]
Yaml is pretty good that way, it uses newlines so you rarely need to quote

**Comment by aneeshusa** [comment]
Rebased again; sorry to make you sit through another Reviewable session!

**Comment by larsbergstrom** [comment]
@edunham I think this is probably good to go, right? At least, reviewable is just telling me it's a rebase with no edits, and I *think* everything is signed off...

**Comment by edunham** [comment]
@larsbergstrom I agree, let's land it now and then test carefully. 

@bors-servo r+

**Pull request merged**
