### PR TITLE
Fix Vagrantfile after #374

### PR DESCRIPTION
**Pull request by aneeshusa**
This is the second time I've broken it, so also add a test.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/394)

### CODE REVIEW

**Comment by aneeshusa** [comment]
r? @larsbergstrom or @edunham 

I haven't had a chance to figure out how to make the smoke test pass on Travis. However, we've gotten a large influx of new contributors that are trying to use the Vagrantfile and are running into the fact that it's broken, so I think it's important it gets fixed ASAP. (See [here](https://github.com/servo/saltfs/issues/407#issuecomment-229760091) and [here](https://github.com/servo/saltfs/pull/431) for examples.) I've updated this to include just the fix for now so we can make it easier for new contributors; the test can be added later.

**Comment by aneeshusa** [comment]
Caught another contributor at #434.

**Comment by edunham** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/394)*

**Comment by aneeshusa** [comment]
@bors-servo r=edunham
Merge conflict was very small (1-2 lines).

**Pull request merged**
