### PR TITLE
Added steps to gzip compress the logs (for servo issue #6399)

### PR DESCRIPTION
**Pull request by Wafflespeanut**
@larsbergstrom What do you think? I also wonder whether it needs to be done for release builds too (?)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@metajack Thanks for your review. Now, would you be kind and close the issue? :)

**Comment by metajack** [comment]
I'll close the bug when the fix gets deployed. I'm waiting for buildbot idle to deploy it.

**Comment by Wafflespeanut** [comment]
@metajack Alright, thanks. Regarding the PR, don't we need to add steps to decompress the logs later?

**Pull request merged**
