### PR TITLE
Infer Buildbot workers from environment

### PR DESCRIPTION
**Pull request by aneeshusa**
Use a dictionary for the lookup.
Make the Environment class (mostly) immutable and hashable to allow
using environment as dictionary keys.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/722)

### CODE REVIEW

**Comment by jdm** [comment]
This looks fine to me.

**Comment by jdm** [comment]
However:
```
[ FAIL ] Buildbot master config check failed:

         Configuration Errors:

           configuration file '/home/servo/buildbot/master/master.cfg' does not exist

[ FAIL ] Buildbot master config lint check failed:

         ./buildbot/master/files/config/environments.py:25:12: E111 indentation is not a multiple of four

         ./buildbot/master/files/config/environments.py:26:12: E111 indentation is not a multiple of four
```

**Comment by jdm** [comment]
Renaming the configuration file will require further changes elsewhere.

**Comment by aneeshusa** [comment]
Oops, renaming the file was meant to be a local-only change for debugging, I had inadvertently committed that before and have removed it now. Yay for tests that catch silly mistakes!

**Pull request closed without merging**
