### PR TITLE
Give jonleighton try access.

### PR DESCRIPTION
**Pull request by emilio**
He's done a bunch of contributions and I'm tired of sending the patches to bors, so this should ensure he can do it :P

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/826)

### CODE REVIEW

**Comment by jonleighton** [comment]
Anyone know what to do about that?

**Comment by jdm** [comment]
Deployed to master.

**Comment by jonleighton** [comment]
Thanks!

**Pull request merged**
