### PR TITLE
Remove old DynamicServoFactory which reads from saltfs

### LINKED ISSUE #316: Move buildbot logic to scripts in `/etc/ci`
Possibly of interest to @shinglyu. 

Right now a lot of build logic is hard-coded in https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/master.cfg . Ideally, Buildbot would only invoke scripts from https://github.com/servo/servo/tree/master/etc/ci. 

It looks like the only templating in `master.cfg` is to insert the value of `common.servo_home`, which is set in https://github.com/servo/saltfs/blob/master/common/map.jinja because it differs between Mac and Linux.

to deploy:

- [x] PR the build scripts to `servo/servo`; land them. servo/servo#10849
- [ ] PR `servo/saltfs` changing buildbot config to invoke the build scripts
- [ ] @larsbergstrom and I will test the buildbot changes on the buildmaster to make sure they work
- [ ] land saltfs PR & highstate servo-master1

### PR DESCRIPTION
**Pull request by aneeshusa**
Now that the new dynamic factory is working (which reads the steps
configuration from the main servo repo), remove the old one.
However, re-use the old name (DynamicServoFactory instead of
DynamicServoYAMLFactory) for concision and clarity.

Fixes #316. Blocked on servo/servo#13611.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/504)

### CODE REVIEW

**Comment by aneeshusa** [comment]
FYI I did this at 2am, so I'd like to take another look in the morning :)

**Comment by aneeshusa** [comment]
servo/servo#13611 has merged, so this is no longer blocked.

**Comment by aneeshusa** [comment]
`steps.yml` was changed, now blocked on a [follow-up PR](https://github.com/servo/saltfs/pull/508#issuecomment-253203920).

**Comment by jdm** [comment]
The followup PR merged. It would be really great to get this reviewed and throw the switch before we change steps.yml again.

**Comment by larsbergstrom** [comment]
This looks good. I think we can land this (even though it'll bitrot my MSVC PR). @aneeshusa Is this good to go?

My only worry is that now to add/change builders we have to do coordinated commits AND buildbot restarts across servo/servo and servo/saltfs and that's certainly going to cause breakage every time we have to do it.

**Comment by aneeshusa** [comment]
Yes, this should be ready. This will optimize for the common case (changing steps for pre-existing builders), and I don't think having to make an extra PR to add/remove a builder (less common) is too onerous.

**Comment by larsbergstrom** [comment]
This has been deployed.

**Comment by larsbergstrom** [comment]
Oh, hrm, should we have removed steps.yml from saltfs, too?

**Comment by aneeshusa** [comment]
I made #513 for that, good call.

**Comment by larsbergstrom** [comment]
What's the easiest way to back this out via salt? The `salt-run` stuff that I did to stage the new mac?

**Comment by aneeshusa** [comment]
If #514 doesn't work, easiest is probably to `git revert` the commits from before this PR up to current master, run a regular highstate, and prepare another PR (with a test builder on Windows!) at our leisure.

The other option is using the override folder and checking out an old git revision, notes at https://github.com/servo/saltfs/blob/b64ff04d219d1fe34c653ae5939f43fc4311d30b/salt/files/master/ADMIN_README.

**Pull request merged**
