### PR TITLE
Re-enable Android states on Travis

### PR DESCRIPTION
**Pull request by aneeshusa**
The larger memory limits on the Trusty beta will
hopefully make these less flaky.

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/145)

### CODE REVIEW

**Comment by aneeshusa** [comment]
I'd recommend trying this build a few times before merging to make sure it's not flaky - I know there have been problems in the past.

**Comment by Manishearth** [comment]
Keeping it closed till the travis build passes.

**Comment by aneeshusa** [comment]
Ok, thanks. Looks like some of the package names may have changed, I'll take a look at it now.

**Comment by Manishearth** [comment]
Cool

**Comment by aneeshusa** [comment]
I fixed the package installation problem, but it looks like it's running into disk space limits.

**Comment by aneeshusa** [comment]
Do you know which components of the SDK/NDK we need? It looks like it may be possible to selectively download the pieces we need: https://sites.google.com/a/android.com/tools/recent/updatingsdkfromcommand-line

**Comment by Manishearth** [comment]
Not sure. @larsbergstrom ?

**Comment by larsbergstrom** [comment]
Platform tools and API 18 at least (it's hard to tell what it *actually* installed). I suspect this will take a little bit of trial and error.

The NDK comes as a big blob. you just have to grab & unpack the binary then also install the specific toolkit (use cmdline in https://github.com/servo/servo/wiki/Building-for-Android#set-up-toolchain).

**Comment by aneeshusa** [comment]
Looks like I got it to build cleanly on Travis! Shame about the build time though.

**Pull request merged**
