### PR TITLE
Add Jeremy as an operator

### PR DESCRIPTION
**Pull request by chenpighead**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/695)

### CODE REVIEW

**Comment by chenpighead** [comment]
Hi, I'd like to get permission to use try and land PRs, so I don't have to keep asking for delegate+ for Bugzilla-reviewed patches.

**Comment by aethanyc** [comment]
@chenpighead is working on stylo. Here's his contribution to servo/servo.
https://github.com/servo/servo/pulls?utf8=%E2%9C%93&q=is%3Apr%20chenpighead

**Comment by chenpighead** [comment]
@aethanyc @jdm ,Thank you! \o/ \o/ \o/

**Pull request merged**
