### PR TITLE
Give review privileges to Nical.

### PR DESCRIPTION
**Pull request by nical**
r? @nox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/666)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Please provide references showing that Nical's reviews have been reviewed by another superreviewer before granting `r+` powers.

A minimal example is https://github.com/servo/saltfs/pull/616, with some relevant links for @avadacatavra.

**Comment by nox** [comment]
For posterity: 

https://github.com/servo/euclid/pull/173
https://github.com/servo/euclid/pull/157
https://github.com/servo/webrender/pull/356
https://github.com/servo/webrender/pull/357

**Comment by Manishearth** [comment]
deployed

**Comment by jdm** [comment]
In hindsight, it may have made more sense to give specific review powers for those repositories instead of general review powers.

**Comment by nical** [comment]
I didn't know we could do that. Don't hesitate to remove my review powers on all repos except euclid and webrender.

**Comment by metajack** [comment]
@jdm I didn't know we could do that either.

**Comment by jdm** [comment]
https://github.com/servo/saltfs/blob/5d3e42b4fde1994589454e63d4e22f0150b2dfe7/homu/files/cfg.toml#L81

**Comment by aneeshusa** [comment]
I've rebased #605 and added a commit there to scope @nical's review privileges to just those two repos.

**Comment by aneeshusa** [comment]
I've [updated the Governance page](https://github.com/servo/servo/wiki/Governance/_compare/5dd23c62a1a1a7a02d95718020068c83e0f0cc57...5b383a57da7be6589d3c3daa7a2478975c2a8ae0) on the wiki to mention the ability to have specific review privileges.

**Comment by metajack** [comment]
Thanks @aneeshusa

**Pull request merged**
