### PR TITLE
Install cmake 3.2 on ubuntu builders.

### PR DESCRIPTION
**Pull request by jdm**
This is needed for https://github.com/servo/servo/pull/19152.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/747)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

Man, we really need to upgrade the builders to a recent Ubuntu.

**Comment by nox** [comment]
Seems like this needs a rebase.

**Comment by jdm** [comment]
No, that's just the new github UI showing that it _could_ be rebased, but there are no actual merge conflicts yet.

**Pull request merged**
