### PR TITLE
Simplify ARM triples, add script to upload ARM tarballs correctly

### PR DESCRIPTION
**Pull request by aneeshusa**
We keep uploading them to the wrong place on accident.

@larsbergstrom ;)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/355)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Looks good!
```
[larsberg@lbergstrom Downloads]$ ./upload-arm.sh arm64-trusty-libs_dbus.tgz arm64 v2
Uploading arm64-trusty-libs_dbus.tgz to s3://servo-rust/ARM/arm64-trusty-libs/v2/arm64-trusty-libs-v2.tgz. Proceed? [Y/n]y
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'arm64-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/arm64-trusty-libs/v2/arm64-trusty-libs-v2.tgz'  [part 1 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in   18s   811.01 kB/s  done
upload: 'arm64-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/arm64-trusty-libs/v2/arm64-trusty-libs-v2.tgz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in   22s   694.62 kB/s  done
upload: 'arm64-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/arm64-trusty-libs/v2/arm64-trusty-libs-v2.tgz'  [part 3 of 3, 5MB] [1 of 1]
 6228187 of 6228187   100% in    6s   975.35 kB/s  done
[larsberg@lbergstrom Downloads]$ ./upload-arm.sh armhf-trusty-libs_dbus.tgz armhf v2
Uploading armhf-trusty-libs_dbus.tgz to s3://servo-rust/ARM/armhf-trusty-libs/v2/armhf-trusty-libs-v2.tgz. Proceed? [Y/n]
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'armhf-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/armhf-trusty-libs/v2/armhf-trusty-libs-v2.tgz'  [part 1 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in   15s   981.77 kB/s  done
upload: 'armhf-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/armhf-trusty-libs/v2/armhf-trusty-libs-v2.tgz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in   15s  1021.19 kB/s  done
upload: 'armhf-trusty-libs_dbus.tgz' -> 's3://servo-rust/ARM/armhf-trusty-libs/v2/armhf-trusty-libs-v2.tgz'  [part 3 of 3, 14MB] [1 of 1]
 14838581 of 14838581   100% in   13s  1067.78 kB/s  done
[larsberg@lbergstrom Downloads]$ 
```

**Comment by larsbergstrom** [comment]
Fix the following and then r=me:
```[ FAIL ] Bad shebangs found in these files:

         ./scripts/upload-arm.sh
```

**Comment by aneeshusa** [comment]
Updated the PR.

I also think it would be prudent to delete all the extra copies of our ARM tarballs that are in unused locations, to decrease the confusion factor in the future.

**Comment by aneeshusa** [comment]
I want to update this to change our URL scheme (yet again!) to get rid of the `download_name` triples in the [map.jinja](https://github.com/servo/saltfs/blob/master/servo-build-dependencies/map.jinja). @larsbergstrom Should I replace them by the `name` or `symlink_name` triples?

**Comment by larsbergstrom** [comment]
@aneeshusa I have no strong opinion - either one would work for me!

**Comment by aneeshusa** [comment]
@larsbergstrom it seems highfive isn't posting its "New code was committed to pull request." comments, but I rebased and updated this to get rid of `download_name`. I also did a lot of renaming so please double-check that I didn't miss something!

**Comment by larsbergstrom** [comment]
@aneeshusa Are you expecting that I will have to re-upload the tarballs before this will work correctly? It did not pass the travis build, due to being unable to find and extract the files from the tarballs (if I'm reading the log correctly).

**Comment by aneeshusa** [comment]
Rebased.

@larsbergstrom yes, in the process of consolidating the triples the URL also changed to be more specific (using the full target triple instead of just `armhf`). Sorry to make you upload the tarballs again! I see it like versioning the Android downloads.

You can cleanup the tarball from the other places we've uploaded it after landing, though.

**Comment by larsbergstrom** [comment]
I think I'm OK with this.

The only question is: should we move the ARM buckets from the servo-rust S3 bucket to one that's in the Servo AWS account? CC: @edunham

**Pull request closed without merging**
