### PR TITLE
Change steps.Git(… method="fresh") to method="clean"

### PR DESCRIPTION
**Pull request by SimonSapin**
http://docs.buildbot.net/latest/manual/cfg-buildsteps.html#git

This will keep the `target` directory between builds, and hopefully reduce build times since not every build will need to recompile everything.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/611)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@metajack Was this deployed? Recent builds are still running `git clean -f -f -d -x` in their "git update" step. For example: http://build.servo.org/builders/mac-rel-css/builds/5996/steps/git/logs/stdio

**Comment by metajack** [comment]
I did the deploy, but perhaps the buildbots don't restart automatically? I will try and confirm.

**Comment by SimonSapin** [comment]
Looks good now.

**Pull request merged**
