### PR TITLE
Add linux-kvm builder type

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/servo/servo/issues/21124

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/850)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m stuck debugging this Travis failure:

```
          ID: /home/servo/buildbot/slave
    Function: file.recurse
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2581, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2458, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1644, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3953, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3623, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'master'
```

`/home/servo/buildbot/slave` is presumably from `buildbot/slave/init.sls`, but `master` does not appear in that file (except in a comment). Jinja usually supports creating backtraces with template source lines, but that’s not happening here so it’s not clear even in which template the error occurs.

Grepping shows:

```
% rg '\{\{.*(\.|\[.)master'
salt/master.sls
65:    - name: {{ salt.master.pkg.name }}
66:    - version: {{ salt.master.pkg.version }}
84:        {{ salt.master.config|yaml(False)|indent(8) }}

buildbot/slave/files/config/buildbot.tac
30:buildmaster_host = '{{ pillar["buildbot"]["master"] }}'
```

… but I don’t know why any of those `master` keys/attributes would be missing.

@aneeshusa, any idea?

**Comment by jdm** [comment]
That is coming from [this line](https://github.com/servo/saltfs/blob/7f9c210acacbf3d8780883d5bd1a2fd39601dbcc/buildbot/slave/files/config/buildbot.tac#L30) of the info.tac jinja template.

**Comment by jdm** [comment]
[this file](https://github.com/servo/saltfs/blob/7f9c210acacbf3d8780883d5bd1a2fd39601dbcc/.travis/test_pillars/top.sls) needs to be modified in order to make the right pillars apply to the new node.

**Comment by SimonSapin** [comment]
Aaaaaah, bitten again by ripgrep ignoring "hidden" files.

**Comment by SimonSapin** [comment]
And it’s green! r? @jdm

**Comment by SimonSapin** [comment]
The parts colored red when deploying this were:

```
          ID: /home/servo/buildbot/slave
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 16:35:57.850025
    Duration: 2075.02 ms
     Changes:   
```
```
          ID: buildbot-slave
    Function: service.running
      Result: False
     Comment: One or more requisite failed: buildbot.slave./home/servo/buildbot/slave
     Started: 
    Duration: 
     Changes:   
```

**Comment by jdm** [comment]
That's https://github.com/servo/saltfs/issues/794. I recommend clearing the fileserver cache and highstating the new build machine directly afterwards.

**Pull request merged**
