### PR TITLE
Avoid installing sccache on servo-master

### PR DESCRIPTION
**Pull request by aneeshusa**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/723)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Follow-up to #688. r? @larsbergstrom

**Comment by aneeshusa** [comment]
Note that when deploying the previous PR, I intentionally did not run the sccache state on `servo-master1`, but just in case it would be good to check for a lurking sccache binary when deploying this.

**Comment by larsbergstrom** [comment]
This lgtm - thanks, aneesh!

@bors-servo r+

**Comment by aneeshusa** [comment]
Looked into the build failure here; we need #724 to be able to merge anything into saltfs.

**Comment by larsbergstrom** [comment]
r=me once 724 lands

**Pull request merged**
