### PR TITLE
[Proposal] Give @heycam reviewer privileges.

### PR DESCRIPTION
**Pull request by emilio**
He is already experienced in the Geckolib side of things, and he is the appropriate person (with @bholley), to review all those style changes.

There have been already a few PRs when he has been delegated before.

This is just a proposal though, what do you think?

cc @larsbergstrom @metajack

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/440)

### CODE REVIEW

**Comment by jdm** [comment]
I am in favour.

**Comment by larsbergstrom** [comment]
Has he reviewed any of the style changes? In general, I just like to make sure that there are at least a few reviews done that have been reviewed by another reviewer before granting r+, even if it seems obvious that the person is reviewer-worthy, to ensure consistent governance.

If that's true, then I'm r+ on that. If not, please just have one of the stylo/style system reviewers watch over a couple of reviews and then comment here and we can grant r+ immediately.

Sorry to be the foot-dragger here! Also, sorry if that was what you meant by "delegated" in your original comment and I'm misinterpreting (assuming here that delegate is homu's delegate, granting the original PR author the ability to r+ after doing fixups).

**Comment by heycam** [comment]
FWIW I have done two Servo reviews so far that I can find, digging back through my email:

* https://github.com/servo/servo/pull/11667
* https://github.com/servo/servo/pull/12339

**Comment by heycam** [comment]
Thanks everyone!

**Comment by larsbergstrom** [comment]
Thanks for helping with reviews! I'll probably have to roll this out tomorrow (US time), as we've got some pending try builds and I don't want to try my luck with rolling out a CI update an hour before sleep :-)

**Comment by larsbergstrom** [comment]
This has been deployed.

**Pull request merged**
