### PR TITLE
Increase client_max_body_size for intermittent-tracker

### LINKED ISSUE #31845: Handle HTTP Error 413: Request Entity Too Large more gracefully.
WPT import currently fails because of it: https://github.com/servo/servo/actions/runs/8405500156/job/23018617126#step:8:14419 and I've hit this when doing webgpu tests too. Ideally if too large we should split it into multiple request.

### PR DESCRIPTION
**Pull request by sagudev**
Should fix https://github.com/servo/servo/issues/31845, but it might be still to low.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]

**Comment by sagudev** [comment]
Is this deployed, so we can test?

**Comment by mrobinson** [comment]
I believe this is deployed now, but I'm always a bit mystified by saltfs, so let me know if there are any issues.

**Comment by sagudev** [comment]
I manually tested with curl, and it seems that it is deployed.

Test WPT import: https://github.com/servo/servo/actions/runs/10281279358

**Comment by sagudev** [comment]
It worked: https://github.com/servo/servo/pull/32959 🎉

**Pull request merged**
