### PR TITLE
Enable homu for servo/gecko-media.

### PR DESCRIPTION
**Pull request by metajack**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/736)

### CODE REVIEW

**Comment by aneeshusa** [comment]
@metajack deployed this and [it's working](https://github.com/servo/gecko-media/pull/35#issuecomment-337449547), so removing the `S-needs-deploy` label. Friendly reminder to remove the label after deploying something :)

**Comment by metajack** [comment]
@aneeshusa sorry about that. I didn't know about that label :(

**Pull request merged**
