### PR TITLE
Add hyper-serde to homu.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/907)

### CODE REVIEW

**Comment by jdm** [comment]
There's something weird about this repository, possibly because it was transferred:
```
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 207, in callback
    repo = get_repo(repo_label, repo_cfg)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 58, in get_repo
    assert repo.owner.login == repo_cfg['owner']
AttributeError: 'NoneType' object has no attribute 'owner'
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 116, in queue
    if repo_label in g.repos and g.repos[repo_label].treeclosed >= 0:
AttributeError: 'NoneType' object has no attribute 'treeclosed'
```

**Comment by nox** [comment]
It's an underscore, not an hyphen. :)

**Comment by jdm** [comment]
```
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 310, in github
    repo_label = g.repo_labels[owner, info['repository']['name']]
KeyError: ('servo', 'hyper_serde')
```
That's from trying to r+ something.
```
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 119, in queue
    g.cfg['repo'][repo_label]['owner'],
KeyError: 'hyper_serde'
```
That's from trying to visit https://build.servo.org/homu/queue/hyper_serde.

**Comment by jdm** [comment]
I deployed the wrong version; now https://build.servo.org/homu/queue/hyper_serde works but I can't make it synchronize.

**Pull request merged**
