### PR TITLE
Salt the Salt master

### LINKED ISSUE #264: Use Salt gitfs to keep master synced with repo
Docs: https://docs.saltstack.com/en/2015.5/topics/tutorials/gitfs.html

Salt has a built-in backend that uses a git repo (such as this one) to provide the files in the /srv/salt tree (the fileserver).

We should use it instead of manually `git pull`ing on the master.

### PR DESCRIPTION
**Pull request by aneeshusa**
Use Salt to install the Salt master.
The Salt master will get restart on configuration changes,
but will need to be manually restarted on package changes to
allow for proper ordering of updating.
(Salt masters must be updated before Salt minions.)

Use Jinja to generate the config file YAML directly, preventing
typos in the master config file and providing access to master
configuration options in the SLS file (e.g. the file_roots locations).

Incorporates and thus fixes #298.

TODO:
  - [x] Add gitfs support. Fixes #264.
  - [x] Add _modules/ dir and backport `launchctl.py` module

TODO after landing:
  - [ ] Add master install instructions to the wiki
  - [ ] Update Salt-inside-Vagrant usage instructions on the wiki 

After I finish the WIP tasks, landing this will unblock a bunch of other things that need the `launchctl.py` module (upgraded ssh, salt-minion salting, upgrading salt, etc.)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/350)

### CODE REVIEW

**Comment by aneeshusa** [comment]
OK, this is ready for review. See the commit messages for details; also, a few notes:
  - The Vagrantfile needed to be updated, so I cherry-picked #298 as well.
  - I tested out the new `launchctl.py` module and updates to the Buildbot slave state on `servo-macpro1` and in Vagrant.

**Comment by aneeshusa** [comment]
Rebased since #298 landed.

**Comment by edunham** [comment]
Reviewed 1 of 11 files at r6, 4 of 4 files at r7, 3 of 3 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[_modules/launchctl.py, line 3 \[r9\]](https://reviewable.io:443/reviews/servo/saltfs/350#-KJbAlojsWZgYiweG_OM:-KJbAlojsWZgYiweG_ON:-574266948) ([raw file](https://github.com/servo/saltfs/blob/a4d30b75d65007fc3fe617a69848f2068eb754dc/_modules/launchctl.py#L3)):*
> ```Python
> # -*- coding: utf-8 -*-
> '''
> Module for the management of MacOS systems that use launchd/launchctl
> ```

It looks like we're vendoring this in from the Salt builtin module (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.launchctl.html). Do we need to worry about keeping this up to date with changes that Salt makes upstream, or will it be obsoleted relatively soon once we upgrade our Salt version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/350)*

**Comment by aneeshusa** [comment]
@edunham I backported that module temporarily; we shouldn't need to update it unless it breaks, and we can simply remove it once we've updated Salt.

I rebased the branch and made some tweaks, but haven't tested them in Vagrant yet because my home Internet connection is slower than at school. Do you know why Travis doesn't seem to be triggering?

**Comment by edunham** [comment]
Not sure what's up with Travis; I've manually restarted https://travis-ci.org/servo/saltfs/builds/128187498 .

**Comment by aneeshusa** [comment]
Rebased, but I want to tweak this a little more before merging.

**Comment by aneeshusa** [comment]
Rebased with tweaks and lightly tested in Vagrant. Ready for review.

**Comment by edunham** [comment]
Reviewed 3 of 4 files at r11, 4 of 4 files at r12, 3 of 3 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/350)*

**Comment by aneeshusa** [comment]
I think I'll need to backport the `pip_state.py` state module as well for this to pass Travis - I'll try to do that this evening.

**Comment by aneeshusa** [comment]
OK, I backported the pip execution and state modules. Something important I discovered is that custom modules with the same name don't work properly, so I prefixed the files with `backported_`.

Should be good to go now.

**Comment by aneeshusa** [comment]
It turns out the file naming wasn't the issue, and that giving the files the same name is the right thing to do for overriding. However, our version of Salt is so old that the backported pip modules weren't working properly (looking for Salt utilities that don't exist in our version), so I've backported only the needed changes to pip_state.py.

Also, I added some headers to (try to) comply with the Apache 2.0 license of the backported modules.

**Comment by aneeshusa** [comment]
All of the test failures are happening on the builders where we test the PR as an upgrade; they fail when applying the initial highstate (of the old code). All of the builders that test the PR from scratch are passing, though, so I think this is OK.

**Comment by larsbergstrom** [comment]
@edunham Is there anything else left to review here? We're having to do all manual merges to saltfs until this lands.

**Comment by edunham** [comment]
Reviewed 2 of 2 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/350)*

**Comment by edunham** [comment]
I think that the problems we're encountering from outdated Salt version are greater than any problems likely to remain in this PR. The Travis failures look like the standard Salt version issues we've been seeing.

**Comment by aneeshusa** [comment]
Just a clarification, this PR doesn't update the whole Salt version, only backports a few modules.

**Pull request merged**
