### PR TITLE
Disable the gczeal builder from auto and force

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @aneeshusa 

Note that I'm leaving the steps around in the hopes that @nox finds a way to make this useful later :-) We might need to split it out into two builds, though.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/385)

### CODE REVIEW

**Comment by aneeshusa** [comment]
This also removes the gczeal builder from try - not sure if you wanted that.

If so, I'd rather remove the steps entirely, as it's easy to get them back from git and they're isolated from other things thanks to steps.yml.

**Comment by aneeshusa** [comment]
You'll also need to remove the actual linux-rel-gczeal builder from the list of builders.

**Comment by aneeshusa** [comment]
Another option is just leaving it around for force, so @nox can run builds from the web UI, but it's not run on auto or try. (At least, I think that's what force is.)

**Comment by larsbergstrom** [comment]
OK, I just removed the whole thing and we can ressurect from the git history if @nox decides he's interested in incremental GC in the future :-)

**Pull request merged**
