### PR TITLE
Add stylo unit tests to linux-dev

### PR DESCRIPTION
**Pull request by Manishearth**
r? @larsbergstrom

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/481)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

```
CommandExecutionError: Command 'git config homebrew.analyticsdisabled "true"' failed. Stderr: 'error: could not lock config file .git/config: No such file or directory'
```

Not sure what this error is; might be a travis intermittent?

**Comment by aneeshusa** [comment]
Just a hunch, but likely related to Homebrew 1.0 and their migration of the homebrew git dir. Will investigate after class. (Also see comments about robustness at #361).

**Comment by Manishearth** [comment]
thanks!

**Comment by aneeshusa** [comment]
Watch #483 for a solution to the Homebrew error.

**Comment by aneeshusa** [comment]
@bors-servo retry
- #483, #492 are merged and OS X biulders are green on Travis again

**Pull request merged**
