### PR TITLE
homu: Take in account ecoal95's username change

### PR DESCRIPTION
**Pull request by emilio**
(that is, me)

r? @larsbergstrom

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/270)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry

Looks like an intermittent package download issue?
```
[0;31m----------[0m
    [0;31m      ID: arm-dependencies[0m
    [0;31mFunction: pkg.installed[0m
    [0;31m  Result: False[0m
    [0;31m Comment: The following packages failed to install/update: g++-arm-linux-gnueabihf, g++-aarch64-linux-gnu[0m
    [0;31m Started: 16:12:55.171223[0m
    [0;31mDuration: 37621.505 ms[0m
```

**Comment by emilio** [comment]
@bors-servo: retry

Same error in the same buildbot... Just to confirm it's not intermittent.

**Comment by emilio** [comment]
Oh, I can't retry yet, ofc

**Pull request merged**
