### PR TITLE
Link a newer openssl from homebrew on OS X

### LINKED ISSUE #210: Need to `brew link --force openssl` on OSX

### PR DESCRIPTION
**Pull request by aneeshusa**
This should be manually tested to a) make sure I didn't break the autoconf linkage, and b) to ensure the openssl linkage works properly.

Closes #210 (for real this time!)

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/218)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Any idea why Travis hasn't picked this up? Hard for me to test locally without #180 (and #181).

**Comment by jdm** [comment]
Yeah, it was missing in the travis console for some reason. It appears to have been picked up now.

**Comment by aneeshusa** [comment]
I put in a fix for Travis and tested this locally on ```servo-macpro1```, so this is ready for review.

Note to self: remember to update the wiki to remove the section about openssl on OS X when this is merged.

**Comment by larsbergstrom** [comment]
@bors-servo r+

Thanks for your continued awesome work on our Salt infra!

**Comment by aneeshusa** [comment]
Weird, I didn't get any emails about this :confused:. Went ahead and updated the wiki.

**Pull request merged**
