### PR TITLE
Add bzbarsky to reviewers.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/607)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@jdm @metajack Looks like there were some reviews by him here:
https://github.com/servo/saltfs/pull/608

Does this look good to one of you two? Seems OK to me :-)

**Comment by metajack** [comment]
In the future, let's have pointers to reviews in the PR description and wait for someone on the core team to approve.

**Pull request merged**
