### PR TITLE
Add my SSH key

### PR DESCRIPTION
**Pull request by o0Ignition0o**
As discussed [here](https://github.com/servo/servo/issues/19505#issuecomment-372131043) and suggested by @jdm, I would like to have access to the mac build machines.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/813)

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
> Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found

I don't think it's related to the PR ^^'

**Comment by jdm** [comment]
I'm investigating that failure in https://github.com/servo/saltfs/issues/814.

**Pull request merged**
