### PR TITLE
Give myself permission to `@bors-servo try`.

### PR DESCRIPTION
**Pull request by notriddle**
[@jdm's idea](https://github.com/servo/servo/pull/8496#issuecomment-156750435)

[Review on Reviewable](https://reviewable.io/reviews/servo/saltfs/162)

### CODE REVIEW

**Comment by Manishearth** [comment]
Seconded, though I don't know what our governance structure is around granting `try`, so I'll wait for @larsbergstrom's seal of approval

**Comment by larsbergstrom** [comment]
@bors-servo r+

Recommendation from a reviewer seems more than adequate, much less *two* of them! CC @metajack in case he wants to discuss more at the next meeting.

**Comment by larsbergstrom** [comment]
```
120.18s$ .travis/install_salt "${TRAVIS_OS_NAME}"

.travis/install_salt: installing salt for Linux

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0

curl: (35) Unknown SSL protocol error in connection to repo.saltstack.com:443 

gpg: no valid OpenPGP data found.

The command ".travis/install_salt "${TRAVIS_OS_NAME}"" failed and exited with 2 during .
```

Hrm, this appears to be an infrastructure error. Sorry for the delay while we sort this out, @notriddle!

**Comment by Manishearth** [comment]
Deployed. Enjoy your new try privileges!

**Comment by notriddle** [comment]
> Deployed. Enjoy your new try privileges!

I'll try.

**Pull request merged**
