### PR TITLE
Fix Homebrew 1.0.0 fallout

### LINKED ISSUE #382: Use OS X 10.11 on Travis
@edunham is [switching all of our Mac builders to OS X 10.11](https://groups.google.com/forum/#!topic/mozilla.dev.servo/KWNQvd3TKPU). Because our Salt states change the underlying system in various ways, they could be affected by the specific OS version, so we should test using the same version.

In order to this, we should set the [`osx_image`](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) key in the `.travis.yml` file for any Mac builders. We'll need to set the value to either `xcode7.3` or `xcode7.2` to get OS X 10.11 - @edunham @larsbergstrom do you know which Xcode we install? (That should also get documented on the wiki.)

### LINKED ISSUE #479: Use environment variables to specify OpenSSL location on OS X
OpenSSL is a key-only homebrew crate, and doing `brew link --force openssl` means we
```
may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
```

Instead, we need to explicitly pass the full include/lib paths to the compiler on our OS X builders, which is most easily done via environment variables.

Parts:
 - Update Salt code to no longer call `brew link --force openssl`
 - Update Buildbot configuration to pass correct values for the `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` environment variables
 - Run some command (TODO: which one?) to unlink openssl on our OS X builders

@santagada Can you give me example output for `"$(brew --prefix)"`? Does this output vary (over time, with openssl package version, randomly, with homebrew updates)? How this varies will inform how we get the right environment variables, due to the property that the Buildbot configuration is executed on the Buildbot master (a Linux machine), not the actual builder. E.g., we may lock down the OpenSSL version and template the string, or we may dynamically get the version, or just wait for the move to NSS/*ring*/crypto-library-of-your-choice-here.

Companion to servo/servo#13225.

### PR DESCRIPTION
**Pull request by aneeshusa**
Homebrew 1.0.0 has just been released with some breaking changes. To handle all of them, this PR has a lot of changes, here are the main points:
- Add a new `homebrew` execution module and `hombrew_analytics` state module to fix analytics disabling
- Fix `autoconf`/`autoconf213` installing and linking
- Use env vars to specify OpenSSL location because linking fails (fixes #479) 
- Upgrade to XCode 8/OS X 10.11 on Travis (fixes #382) to fix installing git
- Update Salt, leaping two major versions ahead to 2016.3.3 (the latest), due to changes in Homebrew Python/Salt packaging not available in our pinned old Salt
- Make our install and dispatch scripts more robust:
  - Force apt-get to use existing configuration files and ignore updates in Salt packages during installation
  - Unlink Salt if we have installed it via Homebrew previously before installing a new one
  - Allow failures when building old revs when checking upgrades (upstreams change)
  - Manually invalidate the Salt cache between runs

See commit messages for full details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/saltfs/483)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Please check my reasoning on the second commit carefully when reviewing.

**Comment by aneeshusa** [comment]
I  also need to update the wiki to add `brew analytics off` to the list of instructions for setting up a new Mac builder.

**Comment by aneeshusa** [comment]
Closing/reopening to retry.

**Comment by Manishearth** [comment]
Reasoning looks fine.

I don't exactly understand what the first commit is about, but comparing with the original code it seems okay too, r=me if that suffices.

(once travis passes)

**Comment by aneeshusa** [comment]
OK, it looks like `brew install` is hanging when installing git. I heard that this now requires XCode 8, so let me try bumping that on Travis.

**Comment by aneeshusa** [comment]
Quick update: I can't figure out how to work around the changes to Homebrew's Salt/Python packaging (they are using a virtualenv now it seems and Salt can't import pip even though it works just find from the command line and pip module works), so this PR now includes a Salt bump to 2016.3.3: two major versions at once!

**Comment by aneeshusa** [comment]
I have battle Homebrew 1.0.0, and now Homebrew has been defeated at great effort.

r? @larsbergstrom @edunham (This is a pretty big PR with big changes, so please let me know if something is iffy or isn't clear.)

**Comment by edunham** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/483)*

**Comment by aneeshusa** [comment]
Updated some of the commit messages to mention any manual migration changes needed. (See also #488.)

**Comment by edunham** [comment]
Reviewed 9 of 9 files at r10, 1 of 1 files at r11, 6 of 6 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/saltfs/483)*

**Comment by larsbergstrom** [comment]
OK, I think that both @edunham and I are good with this. Thanks for all the heavy lifting on this PR! Is it ready to merge and try out?

Also, I'm assuming I will need to pretty much atomically roll this upgrade out to *all* of the machines to get them on the updated salt versions, right? Do the master first, then all the clients?

**Comment by aneeshusa** [comment]
Yeah, this should be good to merge and try out; don't forget the migration steps.

Because we're jumping two major versions, I doubt they will interoperate (as opposed to just one version), so I think an atomic update is best: stop all services, run the upgrade via the install script (instead of raw apt-get or homebrew), restart the master then restart the minions.

**Comment by larsbergstrom** [comment]
Current migration status:
Linux minions all updated fine, but the mac ones are all getting "The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate", which seems to be fixed by doing `salt-key -d {mac}` on the master followed by a reboot. Once the macs are updated, I will try to update the master.

**Comment by larsbergstrom** [comment]
All of the macs respond to a `test.ping` find, but when attempting to highstate with `test=True` I get:
```console
servo-mac2:
    Minion did not return. [No response]
```
The minion logs look like:
```
2016-09-27 15:46:59,144 [salt.minion      ][ERROR   ][328] Error while bringing up minion for multi-master. Is mast
er at servo-master0.servo.org responding?
2016-09-27 15:47:00,220 [salt.loader      ][ERROR   ][449] Exception raised when processing __virtual__ function fo
r mac_system. Module will not be loaded 'service.enable'
2016-09-27 15:47:00,220 [salt.loader      ][WARNING ][449] salt.loaded.int.module.mac_system.__virtual__() is wrong
ly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module '
mac_system', please fix this.
2016-09-27 15:47:28,684 [salt.state       ][ERROR   ][449] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/loader.py", line 1652, in wra
pper
    return f(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/states/user.py", line 457, in
 present
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/loader.py", line 1652, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/states/user.py", line 457, in present
    win_description)
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/states/user.py", line 92, in _changes
    lshad = __salt__['shadow.info'](name)
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/modules/mac_shadow.py", line 160, in info
    'login_failed_count': get_login_failed_count(name),
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/modules/mac_shadow.py", line 255, in get_login_failed_count
    ret = _get_account_policy_data_value(name, 'failedLoginCount')
  File "/usr/local/Cellar/saltstack/2016.3.3/libexec/lib/python2.7/site-packages/salt/modules/mac_shadow.py", line 119, in _get_account_policy_data_value
    raise CommandExecutionError('Unknown error: {0}'.format(exc.strerror))
CommandExecutionError: Unknown error: Command Failed: dscl . -readpl /Users/servo accountPolicyData failedLoginCount
Return Code: 181
Output: No such plist path: failedLoginCount
Error: <dscl_cmd> DS Error: -14261 (eDSUnknownMatchType)


2016-09-27 15:48:15,500 [salt.loader      ][ERROR   ][1065] Exception raised when processing __virtual__ function for mac_system. Module will not be loaded 'service.enabled'
2016-09-27 15:48:15,501 [salt.loader      ][WARNING ][1065] salt.loaded.int.module.mac_system.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_system', please fix this.
2016-09-27 15:48:16,284 [salt.state       ][ERROR   ][1065] The named service buildbot-slave is not available
2016-09-27 15:48:16,291 [salt.loaded.int.module.cmdmod][ERROR   ][1065] Command 'launchctl list buildbot-slave' failed with return code: 113
2016-09-27 15:48:16,292 [salt.loaded.int.module.cmdmod][ERROR   ][1065] stderr: Could not find service "buildbot-slave" in domain for system
2016-09-27 15:48:16,292 [salt.loaded.int.module.cmdmod][ERROR   ][1065] retcode: 113
2016-09-27 15:48:41,252 [salt.minion      ][ERROR   ][328] Error while bringing up minion for multi-master. Is master at servo-master0.servo.org responding?

```

**Comment by larsbergstrom** [comment]
Also, this is basically what I had to do manually:

Linux:
```
service salt-minion stop
curl https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.3/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
printf 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.3 trusty main\n' | sudo tee /etc/apt/sources.list.d/saltstack.list >/dev/null
sudo apt-get -y update
sudo apt-get -y install salt-minion=2016.3.3+ds-1
service salt-minion start
```


Macs:
```
chown -R servo /usr/local

su - servo
brew update
brew unlink saltstack
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9e3a66b6b7ca978bfea86897dcc3391c37f9f0ef/Formula/saltstack.rb
sudo reboot
```

**Comment by aneeshusa** [comment]
I don't think running the old master + new minions will work, you'll probably need to update + restart everything.

Did the install script not work for some reason?

**Comment by larsbergstrom** [comment]
Which scripts? I did the install per the comment about migration steps in: https://github.com/servo/saltfs/pull/483/commits/87d97417bf54ed6745867e1711d41c83e0ab4c91 ?

I also did the master manually on servo-master1. It appears to be the correct version:
```
root@servo-master1:~# salt-master --version
salt-master 2016.3.3 (Boron)
```

**Comment by aneeshusa** [comment]
Sorry, I should have included the link: https://github.com/servo/saltfs/blob/master/.travis/install_salt.sh is the install script (which we use on Travis/in Vagrant), and should also handle upgrades as of this PR.

Taking a look at the highstate failures now.

**Comment by aneeshusa** [comment]
Not sure what the budget looks like, but we could consider spinning up a secondary cluster temporarily to work out the kinks next time we have a big change before changing our production machines.

**Pull request merged**
